<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFzXxXyt\Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFzXxXyt/Combodo_iTop_Portal_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerFzXxXyt.legacy');

    return;
}

if (!\class_exists(Combodo_iTop_Portal_KernelProdContainer::class, false)) {
    \class_alias(\ContainerFzXxXyt\Combodo_iTop_Portal_KernelProdContainer::class, Combodo_iTop_Portal_KernelProdContainer::class, false);
}

return new \ContainerFzXxXyt\Combodo_iTop_Portal_KernelProdContainer([
    'container.build_hash' => 'FzXxXyt',
    'container.build_id' => 'f247f7e5',
    'container.build_time' => 1773059077,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFzXxXyt');
